name: Second workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo some string
        run: echo "Hello World"
      - name: mutiple comands
        run: |
          node -v
          npm -v
  run-macos-commands:
    runs-on: macos-latest
    steps:
      - name: view SW versions
        run: sw_vers
  depends-on-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Outputs "Windows Strings"
      - name: Error step
        run: doesnotexists


